### ISSUE TITLE
Please Delete __pycache__ from GitHub

### ISSUE THREAD

**Issue by gseth** [TTPlanetPig/Comfyui_TTP_Toolset#1]
Hi,

Thanks for this. However please delete __pycache__ form the github. After the custom node install, i was getting black images. Then understood, it messed up comfy nodes.py because my python versi0on is different. I deleted that folder and relaunched comfy and it created new init files in __pycache__

And it working again. Some people might not know this and blame the node as if the ndoe broke comfy when thats not the case.

Thanks.

**Comment by onemonet** [comment]
Indeed, that is the case.

**Comment by TTPlanetPig** [comment]
Thanks for reminder！ done

**Comment by TTPlanetPig** [comment]
_pychae_ deleted
