### ISSUE TITLE
只生成黑图

### ISSUE THREAD

**Issue by blueraincoatli** [TTPlanetPig/Comfyui_TTP_Toolset#5]
所有节点看起来都能正常运行，只是跑出来的图皆为黑图，控制台有一句警告：

██████████████████████████████████████████████████████████████████████████████████| 10/10 [02:14<00:00, 13.46s/it]
#67 [Unknown]: 137.83s
Requested to load AutoencodingEngine
Loading 1 new model
#96 [Unknown]: 8.45s
E:\ComfyUI_windows_portable\ComfyUI\nodes.py:1487: RuntimeWarning: invalid value encountered in cast
  img = Image.fromarray(np.clip(i, 0, 255).astype(np.uint8))
#55 [Unknown]: 0.38s
#74 [Unknown]: 0.43s
Prompt executed in 266.74 seconds

Kimi的分析“具体来说，这段代码试图将一个数组i中的元素限制在0到255之间，然后将其转换为无符号8位整数（np.uint8），并用这个数组创建一个图像对象。如果数组i中存在超出这个范围的值，就会在转换过程中触发这个警告。”

不知是否是黑图的原因？

**Comment by TTPlanetPig** [comment]
我怎么感觉你这里是别的原因造成的，请检查一下，我做这个插件的时候尽最大可能用了comfyui自带的库，所以不应该有奇怪的现象，我这里不处理ksampler采样的。

**Comment by blueraincoatli** [comment]
在我重新替换了VAE Decode节点后，就正常了——同样的comfyUI自带decode Tiled，另外控制台里的那个警告也没了。
