### ISSUE TITLE
ValueError: Crop sizes do not match: (65, 752) vs (64, 752)

### ISSUE THREAD

**Issue by AJbeckliy** [TTPlanetPig/Comfyui_TTP_Toolset#6]
ValueError: Crop sizes do not match: (65, 752) vs (64, 752)
![image](https://github.com/user-attachments/assets/336c114b-60fe-405c-b2b8-13bb3ec6b638)
width_factor and height_factor in the TTP_Tile_image_size node are incorrectly modified.
The image I did the chunking was 1024 by 1024, and I wanted to enlarge it 4x.
Is this value not modifiable? Or do you need to change it in what way?

**Comment by TTPlanetPig** [comment]
I will suggest round your input image before continue. I will add the round logic later

**Comment by TTPlanetPig** [comment]
> ValueError: Crop sizes do not match: (65, 752) vs (64, 752) ![image](https://private-user-images.githubusercontent.com/167010308/363585562-336c114b-60fe-405c-b2b8-13bb3ec6b638.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0MDI1MTcsIm5iZiI6MTcyNzQwMjIxNywicGF0aCI6Ii8xNjcwMTAzMDgvMzYzNTg1NTYyLTMzNmMxMTRiLTYwZmUtNDA1Yy1iMmI4LTEzYmIzZWM2YjYzOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyN1QwMTU2NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MGZiODZjMDFjMzIxYTAxNzM0MzcyNWMxYjMxMGM1ZThjY2M4MWIxY2NkNzFkNDFjZjRjMDNkYzY4NjdhYjk3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.cQMzvSpS8s8TSD_HeVVfPhQA9s_VqbZjiu44ECVy5Dw) width_factor and height_factor in the TTP_Tile_image_size node are incorrectly modified. The image I did the chunking was 1024 by 1024, and I wanted to enlarge it 4x. Is this value not modifiable? Or do you need to change it in what way?

please update to the latest version, it has been fixed!

**Comment by KLL535** [comment]
Same issue. After update to lastest version comfy-ui (cu128)

![Image](https://github.com/user-attachments/assets/4e3b419c-b3cb-4c3d-992c-b40b11477592)

**Comment by r-vage** [comment]
> Same issue. After update to lastest version comfy-ui (cu128)
> 
> ![Image](https://github.com/user-attachments/assets/4e3b419c-b3cb-4c3d-992c-b40b11477592)

as mentioned above rounding you input image will fix this. i ran into the same issue when changing the overlap_rate but resizing the image divisable by 8 fixed it.

<img width="913" height="330" alt="Image" src="https://github.com/user-attachments/assets/43537e9d-e6b7-4055-b274-bb38004ca72a" />
