### ISSUE TITLE
Controlling Image Similarity

### ISSUE THREAD

**Issue by superprat** [TTPlanetPig/Comfyui_TTP_Toolset#9]
The upscale process gives great details with flux, but the image is changing considerably.  I've tried the following things let me know if you recommend any other approaches.

1. Reducing the denoise adds a blurry noise to the whole image, I've tried playing with the steps but anything under 0.5 denoise is overprocessed(?).

![image](https://github.com/user-attachments/assets/681cb2e9-4fbf-4a64-9ac4-f944305a4309)

2. Adding the upscaler controlnet on the tiled conditioning. Is there a way to add this before cond_to_batch. This might require another node to tile the controlnet and apply it correctly.

Any other ideas to control image similarity?

**Comment by TTPlanetPig** [comment]
yes,please update the node, just update the example for pixel application

**Comment by superprat** [comment]
Thank you! That's really helpful 👍🏽 🥇
